import { Inter } from 'next/font/google'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>test</title>
        <meta content='Generated by create next app' name='description' />
        <meta content='width=device-width, initial-scale=1' name='viewport' />
        <link href='/favicon.ico' rel='icon' />
      </Head>
      <h1 className='mx-10 bg-slate-500 p-4 px-4 text-center text-2xl font-bold'>
        Hello bandagram!
      </h1>
    </>
  )
}
