import { Inter } from 'next/font/google'
import Head from 'next/head'

import { getAuthLayout } from '../components/ui/layouts/AuthLayout'
import withAuth from '../hocs/withAuth'

const inter = Inter({ subsets: ['latin'] })

function Home() {
  return (
    <>
      <Head>
        <title>Bandagram</title>
        <meta content='Generated by create next app' name='description' />
        <meta content='width=device-width, initial-scale=1' name='viewport' />
        <link href='/favicon.ico' rel='icon' />
      </Head>
      <h1 className='bg-slate-500 p-4 px-4 text-center text-2xl font-bold'>Hello bandagram!</h1>
    </>
  )
}

const HomeWithAuth = withAuth(Home)

export default HomeWithAuth

// @ts-ignore
HomeWithAuth.getLayout = getAuthLayout
